### ISSUE TITLE
Logik ist doppelt vorhanden

### ISSUE THREAD

**Issue by gossie** [Benet5/ersterFreitag#5]
Wenn ich das richtig sehe, gibt es die Logik doppelt, einmal in `PwValidierung` und in `PwArray `. Besser wäre es, wenn `PwArray` die Methode aus `PwValidierung` aufruft.

**Comment by Benet5** [comment]
Ja, ich hab mir für die bessere Übersicht eine neue Class aufgemacht. Der Output der gesamtCheck-Methode ist unterschiedlich.
